import { Appointment, Barber, Customer, FinancialTransaction, LoyaltyReward, PortfolioPhoto, Review, SalonConfig, Service } from './types';

export const INITIAL_SALON_CONFIG: SalonConfig = {
  name: 'Mamuty Barbearia',
  tagline: 'Mamuty barbearia estilo forte.',
  address: 'Cumaru do Norte - PA, CEP 68398-000, Brasil',
  phone: '(94) 98443-9065',
  whatsappNumber: '5594984439065',
  pixKey: 'hemersonpbarber@gmail.com',
  pixKeyType: 'E-mail',
  pixBeneficiary: 'Mamuty Barbearia (Hemerson Barber)',
  pixCity: 'CUMARU DO NORTE',
  instagram: '@mamutybarbearia',
  openingHours: 'Segunda a Sábado: Somente com hora marcada',
  loyaltyStampsGoal: 10,
};

export const INITIAL_SERVICES: Service[] = [
  { id: 'srv-1', name: 'Corte Tradicional / Tesoura', category: 'cabelo', description: 'Corte masculino completo com alinhamento e finalização.', price: 35, durationMinutes: 40, pointsReward: 35, popular: true },
  { id: 'srv-2', name: 'Degradê / Fade Especial', category: 'cabelo', description: 'Degradê milimétrico na régua (Low, Mid ou High Fade).', price: 35, durationMinutes: 40, pointsReward: 35, popular: true },
  { id: 'srv-3', name: 'Corte Kids Personalizado', category: 'cabelo', description: 'Atendimento especial e personalizado para crianças.', price: 35, durationMinutes: 35, pointsReward: 35, popular: true },
  { id: 'srv-4', name: 'Barba Alinhada & Modelada', category: 'barba', description: 'Desenho, hidratação e toalha para barba perfeita.', price: 25, durationMinutes: 30, pointsReward: 25 },
  { id: 'srv-5', name: 'Combo Mamuty: Cabelo + Barba', category: 'combos', description: 'Corte completo + Barba alinhada no estilo forte Mamuty.', price: 55, durationMinutes: 70, pointsReward: 55, popular: true },
  { id: 'srv-6', name: 'Pezinho & Acabamento Navalhado', category: 'cabelo', description: 'Alinhamento rápido de laterais e nuca na navalha.', price: 15, durationMinutes: 20, pointsReward: 15 }
];

export const INITIAL_BARBERS: Barber[] = [
  { 
    id: 'barber-1', 
    name: 'Hemerson Barber', 
    role: 'Fundador & Barbeiro Chefe', 
    avatarUrl: '/logo.png', 
    rating: 5.0, 
    reviewsCount: 148, 
    specialties: ['Cortes Masculinos', 'Degradê', 'Atendimento Kids Personalizado', 'Barba'], 
    phone: '(94) 98443-9065', 
    bio: 'Fundador da Mamuty Barbearia. Estilo forte, pontualidade britânica e atendimento dedicado a adultos e kids.', 
    availableDays: [1,2,3,4,5,6] 
  },
  { 
    id: 'barber-2', 
    name: 'Carlos Barbeiro', 
    role: 'Especialista em Degradê & Barba', 
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', 
    rating: 4.9, 
    reviewsCount: 88, 
    specialties: ['Fade Navalhado', 'Barboterapia', 'Pezinho'], 
    phone: '(94) 98443-9065', 
    bio: 'Precisão milimétrica e acabamento na régua.', 
    availableDays: [1,2,3,4,5,6] 
  },
  { 
    id: 'barber-3', 
    name: 'Marcos Barbeiro', 
    role: 'Especialista em Corte Clássico & Kids', 
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80', 
    rating: 4.9, 
    reviewsCount: 92, 
    specialties: ['Corte Tradicional', 'Atendimento Infantil', 'Sobrancelha'], 
    phone: '(94) 98443-9065', 
    bio: 'Paciência no atendimento kids e visual clássico de respeito.', 
    availableDays: [1,2,3,4,5,6] 
  },
];

export const INITIAL_LOYALTY_REWARDS: LoyaltyReward[] = [
  {
    id: 'rew-1',
    title: '50% OFF no Próximo Corte',
    description: 'Válido para qualquer modalidade de corte de cabelo.',
    pointsCost: 250,
    stampsRequired: 5,
    badge: '5 Selos',
    type: 'stamps',
  },
  {
    id: 'rew-2',
    title: 'Corte ou Barboterapia GRÁTIS',
    description: 'Complete 10 selos no seu cartão fidelidade e ganhe um atendimento 100% gratuito!',
    pointsCost: 500,
    stampsRequired: 10,
    badge: '10 Selos (Grátis)',
    type: 'stamps',
  },
  {
    id: 'rew-3',
    title: 'Pomada Modeladora Efeito Matte',
    description: 'Resgate um pote da pomada premium exclusiva Mamuty Barbearia.',
    pointsCost: 350,
    badge: '350 Pontos',
    type: 'points',
  },
  {
    id: 'rew-4',
    title: 'Óleo Hidratante para Barba',
    description: 'Óleo nobre com aroma de sândalo e cravo para maciez e brilho da barba.',
    pointsCost: 300,
    badge: '300 Pontos',
    type: 'points',
  },
  {
    id: 'rew-5',
    title: 'Cerveja Artesanal IPA Mamuty',
    description: 'Deguste uma gelada especial durante o seu atendimento.',
    pointsCost: 100,
    badge: '100 Pontos',
    type: 'points',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    customerName: 'Carlos Eduardo Mendes',
    barberId: 'barber-1',
    barberName: 'Rafael "Mamuty" Costa',
    rating: 5,
    comment: 'Atendimento fora de série! O visagismo mudou completamente o formato que eu usava no cabelo. Ambiente impecável, café de qualidade e pontualidade britânica.',
    tags: ['Visagismo Top', 'Pontualidade', 'Ambiente 10/10'],
    createdAt: '2026-09-04T15:30:00Z',
  },
  {
    id: 'rev-2',
    customerName: 'Thiago Almeida',
    barberId: 'barber-3',
    barberName: 'Gabriel Santos',
    rating: 5,
    comment: 'A barboterapia do Gabriel é uma verdadeira terapia depois de um dia pesado de trabalho. A toalha quente e a massagem facial fazem toda diferença.',
    tags: ['Barboterapia', 'Relaxamento', 'Mão Leve'],
    createdAt: '2026-09-03T18:10:00Z',
  },
  {
    id: 'rev-3',
    customerName: 'Rodrigo Fontes',
    barberId: 'barber-2',
    barberName: 'Marcos Silva',
    rating: 5,
    comment: 'Melhor degradê de São Paulo sem dúvidas! O Marcos tem uma mão muito precisa, o fade fica limpo por mais de duas semanas.',
    tags: ['Degradê Impecável', 'Precisão'],
    createdAt: '2026-09-02T11:45:00Z',
  },
  {
    id: 'rev-4',
    customerName: 'Felipe Santana',
    barberId: 'barber-1',
    barberName: 'Rafael "Mamuty" Costa',
    rating: 5,
    comment: 'O app é sensacional, agendei em menos de 1 minuto e a confirmação no WhatsApp com o lembrete me salvou de esquecer o horário!',
    tags: ['Agendamento Rápido', 'Notificação WhatsApp'],
    createdAt: '2026-08-30T17:20:00Z',
  },
  {
    id: 'rev-5',
    customerName: 'Bruno Henrique',
    barberId: 'barber-4',
    barberName: 'Lucas Barreto',
    rating: 4,
    comment: 'Corte ficou show e o estilo muito moderno. Voltarei com certeza para fazer a barba.',
    tags: ['Estilo Moderno', 'Profissional'],
    createdAt: '2026-08-28T14:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cli-1',
    name: 'Carlos Eduardo Mendes',
    phone: '11998765432',
    email: 'carlos.mendes@email.com',
    totalVisits: 8,
    totalSpent: 820,
    loyaltyStamps: 8,
    loyaltyPoints: 480,
    tier: 'Ouro VIP',
    lastVisit: '2026-09-04',
    preferredBarberId: 'barber-1',
    notes: 'Prefere corte com tesoura nas pontas e café expresso duplo.',
  },
  {
    id: 'cli-2',
    name: 'Thiago Almeida',
    phone: '11987654321',
    email: 'thiago.almeida@email.com',
    totalVisits: 5,
    totalSpent: 490,
    loyaltyStamps: 5,
    loyaltyPoints: 290,
    tier: 'Prata',
    lastVisit: '2026-09-03',
    preferredBarberId: 'barber-3',
    notes: 'Pele sensível na lâmina, usar pós-barba sem álcool.',
  },
  {
    id: 'cli-3',
    name: 'Rodrigo Fontes',
    phone: '11976543210',
    email: 'rodrigo.fontes@email.com',
    totalVisits: 12,
    totalSpent: 1350,
    loyaltyStamps: 2, // Já resgatou 10 selos anteriormente, no ciclo 2
    loyaltyPoints: 620,
    tier: 'Ouro VIP',
    lastVisit: '2026-09-02',
    preferredBarberId: 'barber-2',
    notes: 'Cliente fiel semanal. Gosta de fade militar baixo.',
  },
  {
    id: 'cli-4',
    name: 'Felipe Santana',
    phone: '11965432109',
    email: 'felipe.santana@email.com',
    totalVisits: 3,
    totalSpent: 270,
    loyaltyStamps: 3,
    loyaltyPoints: 170,
    tier: 'Bronze',
    lastVisit: '2026-08-30',
    preferredBarberId: 'barber-1',
  },
  {
    id: 'cli-5',
    name: 'Matheus Nogueira',
    phone: '11954321098',
    email: 'matheus.n@email.com',
    totalVisits: 6,
    totalSpent: 590,
    loyaltyStamps: 6,
    loyaltyPoints: 340,
    tier: 'Prata',
    lastVisit: '2026-08-25',
    preferredBarberId: 'barber-2',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  { id: 'apt-1', customerName: 'João Silva', customerPhone: '11999999999', serviceIds: ['srv-1'], serviceNames: ['Corte'], totalPrice: 35, totalDurationMinutes: 40, barberId: 'barber-1', barberName: 'João', date: new Date().toISOString().split('T')[0], time: '14:00', status: 'confirmed', paymentMethod: 'presencial', paymentStatus: 'no_local', whatsappNotificationSent: false, createdAt: new Date().toISOString() },
  { id: 'apt-2', customerName: 'Carlos Silva', customerPhone: '11999999999', serviceIds: ['srv-2'], serviceNames: ['Barba'], totalPrice: 25, totalDurationMinutes: 30, barberId: 'barber-2', barberName: 'Carlos', date: new Date().toISOString().split('T')[0], time: '15:30', status: 'confirmed', paymentMethod: 'presencial', paymentStatus: 'no_local', whatsappNotificationSent: false, createdAt: new Date().toISOString() },
  { id: 'apt-3', customerName: 'Pedro Silva', customerPhone: '11999999999', serviceIds: ['srv-3'], serviceNames: ['Corte + Barba'], totalPrice: 55, totalDurationMinutes: 70, barberId: 'barber-3', barberName: 'Pedro', date: new Date().toISOString().split('T')[0], time: '16:00', status: 'confirmed', paymentMethod: 'presencial', paymentStatus: 'no_local', whatsappNotificationSent: false, createdAt: new Date().toISOString() }
];

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'tx-1',
    appointmentId: 'apt-100',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 125,
    date: '2026-09-02',
    paymentMethod: 'pix',
    description: 'Atendimento Rodrigo Fontes - Degradê + Barboterapia',
    barberId: 'barber-2',
  },
  {
    id: 'tx-2',
    appointmentId: 'apt-101',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 110,
    date: '2026-09-06',
    paymentMethod: 'pix',
    description: 'Atendimento Carlos Mendes - Combo Mamuty VIP',
    barberId: 'barber-1',
  },
  {
    id: 'tx-3',
    appointmentId: 'apt-102',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 70,
    date: '2026-09-06',
    paymentMethod: 'cartao',
    description: 'Atendimento Lucas Ferreira - Fade Navalhado',
    barberId: 'barber-2',
  },
  {
    id: 'tx-4',
    type: 'receita',
    category: 'Venda de Produtos',
    amount: 85,
    date: '2026-09-05',
    paymentMethod: 'cartao',
    description: 'Venda de 1 Pomada Matte + 1 Óleo para Barba Mamuty',
  },
  {
    id: 'tx-5',
    type: 'despesa',
    category: 'Insumos e Lâminas',
    amount: 140,
    date: '2026-09-04',
    paymentMethod: 'pix',
    description: 'Compra de caixas de lâminas descartáveis e toalhas esterilizadas',
  },
  {
    id: 'tx-6',
    type: 'despesa',
    category: 'Frigobar & Café Especial',
    amount: 95,
    date: '2026-09-03',
    paymentMethod: 'pix',
    description: 'Reposição de grãos de café gourmet e cervejas artesanais cortesia',
  },
  {
    id: 'tx-7',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 180,
    date: '2026-09-04',
    paymentMethod: 'pix',
    description: 'Atendimentos de quarta-feira tarde',
    barberId: 'barber-3',
  },
];

export const INITIAL_PORTFOLIO: PortfolioPhoto[] = [
  // Matheus "Mamuty" Rocha (Fundador & Master Barber) - Visagismo, Tesoura Clássica, Fade Esculpido, Barboterapia
  {
    id: 'port-1',
    barberId: 'barber-1',
    barberName: 'Matheus "Mamuty" Rocha',
    barberAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    title: 'Pompadour Texturizado & Fade Esculpido',
    styleTag: 'Pompadour Clássico',
    category: 'classico',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&auto=format&fit=crop&q=80',
    description: 'Transição suave iniciada na navalha com topo estruturado em tesoura fio navalha. Finalização com spray de fixação e pomada matte fosca.',
    likesCount: 184,
    createdAt: '2026-09-04',
    suggestedServiceName: 'Combo Mamuty Imperial (Corte + Barba)',
  },
  {
    id: 'port-2',
    barberId: 'barber-1',
    barberName: 'Matheus "Mamuty" Rocha',
    barberAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    title: 'Corte Executivo com Visagismo Sob Medida',
    styleTag: 'Tesoura & Visagismo',
    category: 'classico',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    description: 'Harmonização de traços faciais através de proporções balanceadas na tesoura. Linhas limpas e perfil discreto para ambientes corporativos.',
    likesCount: 142,
    createdAt: '2026-09-02',
    suggestedServiceName: 'Corte Tradicional & Tesoura',
  },
  {
    id: 'port-3',
    barberId: 'barber-1',
    barberName: 'Matheus "Mamuty" Rocha',
    barberAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    title: 'Barba Esculpida & Alinhamento Milimétrico',
    styleTag: 'Barba de Respeito',
    category: 'barba',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    description: 'Contorno de bochechas com navalhete descartável e toalha quente com essência de menta e eucalipto para abrir poros sem irritação.',
    likesCount: 226,
    createdAt: '2026-08-30',
    suggestedServiceName: 'Barboterapia & Toalha Quente',
  },

  // Diego Alcantara (Especialista em Degradê & Fade) - Low Fade, Mid Fade, Texturização, Taper Fade
  {
    id: 'port-4',
    barberId: 'barber-2',
    barberName: 'Diego Alcantara',
    barberAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    title: 'Mid Skin Fade com Texturização Francesa (Crop)',
    styleTag: 'Mid Skin Fade',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1567894340315-735d7c361db0?w=800&auto=format&fit=crop&q=80',
    description: 'Degradê em 4 alturas partindo da pele com sombreamento uniforme sem marcas. Topo em mechas curtas texturizadas para visual moderno despojado.',
    likesCount: 310,
    createdAt: '2026-09-05',
    suggestedServiceName: 'Corte Degradê / Fade Navalhado',
  },
  {
    id: 'port-5',
    barberId: 'barber-2',
    barberName: 'Diego Alcantara',
    barberAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    title: 'Low Taper Fade Urbano com Pezinho Alinhado',
    styleTag: 'Taper Fade',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1517832606589-7629c339590a?w=800&auto=format&fit=crop&q=80',
    description: 'Desvanecimento apenas nas costeletas e na nuca, preservando o volume denso das laterais. Acabamento afiado nas têmporas com navalha.',
    likesCount: 195,
    createdAt: '2026-09-01',
    suggestedServiceName: 'Corte Degradê / Fade Navalhado',
  },
  {
    id: 'port-6',
    barberId: 'barber-2',
    barberName: 'Diego Alcantara',
    barberAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    title: 'High Fade com Topete Alto Desconectado',
    styleTag: 'High Fade Navalhado',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&auto=format&fit=crop&q=80',
    description: 'Raspagem alta com transição limpa para clientes que buscam impacto e frescor. Secagem com escova redonda e pasta modeladora.',
    likesCount: 168,
    createdAt: '2026-08-28',
    suggestedServiceName: 'Corte Degradê / Fade Navalhado',
  },

  // Gabriel Santos (Master Barboterapeuta) - Barboterapia, Desenho de Barba, Navalha Tradicional
  {
    id: 'port-7',
    barberId: 'barber-3',
    barberName: 'Gabriel Santos',
    barberAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    title: 'Barboterapia Completa & Ritual da Toalha Quente',
    styleTag: 'Barboterapia Relaxante',
    category: 'barba',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    description: 'Procedimento com vaporizador de ozônio, esfoliação facial revigorante, loção pós-barba hidratante e massagem manual relaxante.',
    likesCount: 284,
    createdAt: '2026-09-03',
    suggestedServiceName: 'Barboterapia & Toalha Quente',
  },
  {
    id: 'port-8',
    barberId: 'barber-3',
    barberName: 'Gabriel Santos',
    barberAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    title: 'Barba Cheia Lenhador com Contornos Afiados',
    styleTag: 'Barba Lenhador (Lumberjack)',
    category: 'barba',
    imageUrl: 'https://images.unsplash.com/photo-1593702295094-ada7554100c3?w=800&auto=format&fit=crop&q=80',
    description: 'Aparação de pontas duplas, hidratação profunda com blend de óleos vegetais e desenho simétrico do bigode e queixo.',
    likesCount: 209,
    createdAt: '2026-08-29',
    suggestedServiceName: 'Combo Mamuty Imperial (Corte + Barba)',
  },
  {
    id: 'port-9',
    barberId: 'barber-3',
    barberName: 'Gabriel Santos',
    barberAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    title: 'Design de Barba Degradê com Camuflagem',
    styleTag: 'Barba Fade',
    category: 'barba',
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&auto=format&fit=crop&q=80',
    description: 'Graduação do pelo da barba conectando com a costeleta do cabelo. Camuflagem suave de fios brancos com tonalizante sem amônia.',
    likesCount: 173,
    createdAt: '2026-08-26',
    suggestedServiceName: 'Camuflagem de Cabelo / Barba',
  },

  // Lucas Barreto (Barbeiro & Estilista) - Freestyle, Camuflagem, Cabelo Longo Masculino
  {
    id: 'port-10',
    barberId: 'barber-4',
    barberName: 'Lucas Barreto',
    barberAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
    title: 'Freestyle Artístico com Linhas Geométricas',
    styleTag: 'Freestyle Navalhado',
    category: 'freestyle',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
    description: 'Desenho exclusivo esculpido diretamente com navalhete de precisão e máquina de acabamento zero. Estilo autêntico e moderno.',
    likesCount: 345,
    createdAt: '2026-09-05',
    suggestedServiceName: 'Corte Degradê / Fade Navalhado',
  },
  {
    id: 'port-11',
    barberId: 'barber-4',
    barberName: 'Lucas Barreto',
    barberAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
    title: 'Platinado Global Ice White com Skin Fade',
    styleTag: 'Platinado Nevou',
    category: 'platinado',
    imageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800&auto=format&fit=crop&q=80',
    description: 'Descoloração em duas sessões com protetor de couro cabeludo e matização acinzentada. Finalizado com hidratação reconstrutora.',
    likesCount: 412,
    createdAt: '2026-09-02',
    suggestedServiceName: 'Tratamento & Hidratação Capilar',
  },
  {
    id: 'port-12',
    barberId: 'barber-4',
    barberName: 'Lucas Barreto',
    barberAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
    title: 'Quiff Texturizado & Acabamento Desconectado',
    styleTag: 'Messy Quiff Moderno',
    category: 'classico',
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80',
    description: 'Corte com navalha desfiadeira para conferir movimento e leveza. Ideal para usar solto no dia a dia com pó modelador volumizador.',
    likesCount: 198,
    createdAt: '2026-08-27',
    suggestedServiceName: 'Corte Tradicional & Tesoura',
  },
];
