import { Appointment, Barber, Customer, FinancialTransaction, LoyaltyReward, PortfolioPhoto, Review, SalonConfig, Service } from './types';

export const INITIAL_SALON_CONFIG: SalonConfig = {
  name: 'Mamuty Barbearia',
  tagline: 'Mamuty barbearia estilo forte.',
  address: 'Cumaru do Norte - PA, CEP 68398-000, Brasil',
  phone: '(94) 98443-9065',
  whatsappNumber: '5594984439065',
  pixKey: 'hemersonpbarber@gmail.com',
  pixKeyType: 'E-mail',
  pixBeneficiary: 'Mamuty Barbearia (Hemerson Barber)',
  pixCity: 'CUMARU DO NORTE',
  instagram: '@mamutybarbearia',
  openingHours: 'Segunda a Sábado: Somente com hora marcada',
  loyaltyStampsGoal: 10,
  toleranceMinutes: 15,
};

export const INITIAL_SERVICES: Service[] = [
  { id: 'srv-1', name: 'Corte social', category: 'cabelo', description: 'Corte masculino tradicional com alinhamento na tesoura ou máquina.', price: 40, durationMinutes: 30, pointsReward: 40, popular: true },
  { id: 'srv-2', name: 'Corte degradê', category: 'cabelo', description: 'Degradê milimétrico na régua (Low, Mid ou High Fade).', price: 40, durationMinutes: 40, pointsReward: 40, popular: true },
  { id: 'srv-3', name: 'Barba simples', category: 'barba', description: 'Alinhamento e desenho de barba com toalha e navalha.', price: 35, durationMinutes: 30, pointsReward: 35 },
  { id: 'srv-4', name: 'Cabelo + Barba', category: 'combos', description: 'Combo completo de corte degradê ou tradicional + barba alinhada.', price: 70, durationMinutes: 50, pointsReward: 70, popular: true },
  { id: 'srv-5', name: 'Cabelo + Sobrancelha', category: 'combos', description: 'Corte de cabelo completo com alinhamento e limpeza de sobrancelha.', price: 60, durationMinutes: 45, pointsReward: 60 },
  { id: 'srv-6', name: 'Combo Completo', category: 'combos', description: 'Corte completo, barba na toalha quente, sobrancelha e finalização.', price: 100, durationMinutes: 60, pointsReward: 100, popular: true }
];

export const INITIAL_BARBERS: Barber[] = [
  { 
    id: 'barber-1', 
    name: 'Hemerson', 
    role: 'Fundador & Barbeiro Chefe', 
    avatarUrl: '/barber-hemerson.jpg', 
    rating: 5.0, 
    reviewsCount: 148, 
    specialties: ['Corte de cabelo degradê', 'Tesoura', 'Barba', 'Kids'], 
    phone: '(94) 98443-9065', 
    bio: 'Fundador da Mamuty Barbearia. Estilo forte, pontualidade britânica e atendimento dedicado a adultos e kids.', 
    availableDays: [1,2,3,4,5,6] 
  },
  { 
    id: 'barber-2', 
    name: 'Douglas', 
    role: 'Especialista em Degradê & Barba', 
    avatarUrl: '/barber-douglas.jpg', 
    rating: 4.9, 
    reviewsCount: 112, 
    specialties: ['Corte de cabelo degradê', 'Fade Navalhado', 'Barboterapia', 'Pezinho'], 
    phone: '(94) 98443-9065', 
    bio: 'Precisão milimétrica e acabamento na régua.', 
    availableDays: [1,2,3,4,5,6] 
  },
];

export const INITIAL_LOYALTY_REWARDS: LoyaltyReward[] = [
  {
    id: 'rew-1',
    title: '50% OFF no Próximo Corte',
    description: 'Válido para qualquer modalidade de corte de cabelo.',
    pointsCost: 250,
    stampsRequired: 5,
    badge: '5 Selos',
    type: 'stamps',
  },
  {
    id: 'rew-2',
    title: 'Corte ou Barboterapia GRÁTIS',
    description: 'Complete 10 selos no seu cartão fidelidade e ganhe um atendimento 100% gratuito!',
    pointsCost: 500,
    stampsRequired: 10,
    badge: '10 Selos (Grátis)',
    type: 'stamps',
  },
  {
    id: 'rew-3',
    title: 'Pomada Modeladora Efeito Matte',
    description: 'Resgate um pote da pomada premium exclusiva Mamuty Barbearia.',
    pointsCost: 350,
    badge: '350 Pontos',
    type: 'points',
  },
  {
    id: 'rew-4',
    title: 'Óleo Hidratante para Barba',
    description: 'Óleo nobre com aroma de sândalo e cravo para maciez e brilho da barba.',
    pointsCost: 300,
    badge: '300 Pontos',
    type: 'points',
  },
  {
    id: 'rew-5',
    title: 'Cerveja Artesanal IPA Mamuty',
    description: 'Deguste uma gelada especial durante o seu atendimento.',
    pointsCost: 100,
    badge: '100 Pontos',
    type: 'points',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    customerName: 'Carlos Eduardo Mendes',
    barberId: 'barber-1',
    barberName: 'Hemerson',
    rating: 5,
    comment: 'Atendimento fora de série! O degradê e o alinhamento ficaram perfeitos. Estilo forte e pontualidade britânica.',
    tags: ['Degradê Impecável', 'Pontualidade', 'Ambiente 10/10'],
    createdAt: '2026-09-04T15:30:00Z',
  },
  {
    id: 'rev-2',
    customerName: 'Thiago Almeida',
    barberId: 'barber-2',
    barberName: 'Douglas',
    rating: 5,
    comment: 'O atendimento com a toalha e o cuidado na barba é excelente. Ambiente de primeira e atendimento rápido sem enrolação!',
    tags: ['Barboterapia', 'Relaxamento', 'Mão Leve'],
    createdAt: '2026-09-03T18:10:00Z',
  },
  {
    id: 'rev-3',
    customerName: 'Rodrigo Fontes',
    barberId: 'barber-1',
    barberName: 'Hemerson',
    rating: 5,
    comment: 'Melhor barbearia de Cumaru do Norte sem dúvidas! O corte navalhado dura muito tempo impecável e o agendamento no app facilita demais.',
    tags: ['Degradê Impecável', 'Precisão'],
    createdAt: '2026-09-02T11:45:00Z',
  },
  {
    id: 'rev-4',
    customerName: 'Felipe Santana',
    barberId: 'barber-1',
    barberName: 'Hemerson',
    rating: 5,
    comment: 'Trouxe meu filho para o corte kids e o atendimento foi nota 10. Muita paciência e o corte ficou estiloso demais.',
    tags: ['Atendimento Kids', 'Profissionalismo'],
    createdAt: '2026-08-30T17:20:00Z',
  },
  {
    id: 'rev-5',
    customerName: 'Bruno Henrique',
    barberId: 'barber-2',
    barberName: 'Douglas',
    rating: 5,
    comment: 'O app é sensacional, agendei em 30 segundos e a confirmação no WhatsApp garante tudo sem precisar ficar ligando. Top!',
    tags: ['Agendamento Rápido', 'Notificação WhatsApp'],
    createdAt: '2026-08-28T14:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cli-1',
    name: 'Carlos Eduardo Mendes',
    phone: '11998765432',
    email: 'carlos.mendes@email.com',
    totalVisits: 8,
    totalSpent: 820,
    loyaltyStamps: 8,
    loyaltyPoints: 480,
    tier: 'Ouro VIP',
    lastVisit: '2026-09-04',
    preferredBarberId: 'barber-1',
    notes: 'Prefere corte com tesoura nas pontas e café expresso duplo.',
  },
  {
    id: 'cli-2',
    name: 'Thiago Almeida',
    phone: '11987654321',
    email: 'thiago.almeida@email.com',
    totalVisits: 5,
    totalSpent: 490,
    loyaltyStamps: 5,
    loyaltyPoints: 290,
    tier: 'Prata',
    lastVisit: '2026-09-03',
    preferredBarberId: 'barber-2',
    notes: 'Pele sensível na lâmina, usar pós-barba sem álcool.',
  },
  {
    id: 'cli-3',
    name: 'Rodrigo Fontes',
    phone: '11976543210',
    email: 'rodrigo.fontes@email.com',
    totalVisits: 12,
    totalSpent: 1350,
    loyaltyStamps: 2,
    loyaltyPoints: 620,
    tier: 'Ouro VIP',
    lastVisit: '2026-09-02',
    preferredBarberId: 'barber-1',
    notes: 'Cliente fiel semanal. Gosta de fade militar baixo.',
  },
  {
    id: 'cli-4',
    name: 'Felipe Santana',
    phone: '11965432109',
    email: 'felipe.santana@email.com',
    totalVisits: 3,
    totalSpent: 270,
    loyaltyStamps: 3,
    loyaltyPoints: 170,
    tier: 'Bronze',
    lastVisit: '2026-08-30',
    preferredBarberId: 'barber-1',
  },
  {
    id: 'cli-5',
    name: 'Matheus Nogueira',
    phone: '11954321098',
    email: 'matheus.n@email.com',
    totalVisits: 6,
    totalSpent: 590,
    loyaltyStamps: 6,
    loyaltyPoints: 340,
    tier: 'Prata',
    lastVisit: '2026-08-25',
    preferredBarberId: 'barber-2',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    customerName: 'Cliente X',
    customerPhone: '94991112233',
    serviceIds: ['srv-2'],
    serviceNames: ['Corte degradê'],
    totalPrice: 40,
    totalDurationMinutes: 40,
    barberId: 'barber-1',
    barberName: 'Hemerson',
    date: new Date().toISOString().split('T')[0],
    time: '09:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'apt-2',
    customerName: 'Cliente Y',
    customerPhone: '94992223344',
    serviceIds: ['srv-3'],
    serviceNames: ['Barba simples'],
    totalPrice: 35,
    totalDurationMinutes: 30,
    barberId: 'barber-2',
    barberName: 'Douglas',
    date: new Date().toISOString().split('T')[0],
    time: '10:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'apt-3',
    customerName: 'Cliente Z',
    customerPhone: '94993334455',
    serviceIds: ['srv-1'],
    serviceNames: ['Corte social'],
    totalPrice: 40,
    totalDurationMinutes: 30,
    barberId: 'barber-1',
    barberName: 'Hemerson',
    date: new Date().toISOString().split('T')[0],
    time: '14:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'apt-4',
    customerName: 'Marcos Souza',
    customerPhone: '94994445566',
    serviceIds: ['srv-4'],
    serviceNames: ['Cabelo + Barba'],
    totalPrice: 70,
    totalDurationMinutes: 50,
    barberId: 'barber-2',
    barberName: 'Douglas',
    date: new Date().toISOString().split('T')[0],
    time: '16:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'tx-1',
    appointmentId: 'apt-100',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 125,
    date: '2026-09-02',
    paymentMethod: 'pix',
    description: 'Atendimento Rodrigo Fontes - Degradê + Barba',
    barberId: 'barber-1',
  },
  {
    id: 'tx-2',
    appointmentId: 'apt-101',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 110,
    date: '2026-09-06',
    paymentMethod: 'pix',
    description: 'Atendimento Carlos Mendes - Combo Completo',
    barberId: 'barber-1',
  },
  {
    id: 'tx-3',
    appointmentId: 'apt-102',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 70,
    date: '2026-09-06',
    paymentMethod: 'cartao',
    description: 'Atendimento Lucas Ferreira - Cabelo + Barba',
    barberId: 'barber-2',
  },
  {
    id: 'tx-4',
    type: 'receita',
    category: 'Venda de Produtos',
    amount: 85,
    date: '2026-09-05',
    paymentMethod: 'cartao',
    description: 'Venda de 1 Pomada Matte + 1 Óleo para Barba',
  },
  {
    id: 'tx-5',
    type: 'despesa',
    category: 'Insumos e Lâminas',
    amount: 140,
    date: '2026-09-04',
    paymentMethod: 'pix',
    description: 'Compra de caixas de lâminas descartáveis e toalhas esterilizadas',
  },
  {
    id: 'tx-6',
    type: 'despesa',
    category: 'Frigobar & Café Especial',
    amount: 95,
    date: '2026-09-03',
    paymentMethod: 'pix',
    description: 'Reposição de grãos de café gourmet e cervejas artesanais cortesia',
  },
  {
    id: 'tx-7',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 180,
    date: '2026-09-04',
    paymentMethod: 'pix',
    description: 'Atendimentos de quarta-feira tarde',
    barberId: 'barber-2',
  },
];

export const INITIAL_PORTFOLIO: PortfolioPhoto[] = [
  {
    id: 'port-1',
    barberId: 'barber-1',
    barberName: 'Hemerson',
    barberAvatar: '/barber-hemerson.jpg',
    title: 'Pompadour Texturizado & Fade Esculpido',
    styleTag: 'Pompadour Clássico',
    category: 'classico',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&auto=format&fit=crop&q=80',
    description: 'Transição suave iniciada na navalha com topo estruturado em tesoura. Finalização com pomada matte.',
    likesCount: 184,
    createdAt: '2026-09-04',
    suggestedServiceName: 'Cabelo + Barba',
  },
  {
    id: 'port-2',
    barberId: 'barber-1',
    barberName: 'Hemerson',
    barberAvatar: '/barber-hemerson.jpg',
    title: 'Corte Tradicional com Visagismo',
    styleTag: 'Tesoura & Visagismo',
    category: 'classico',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    description: 'Harmonização de traços faciais through de proporções balanceadas na tesoura.',
    likesCount: 142,
    createdAt: '2026-09-02',
    suggestedServiceName: 'Corte social',
  },
  {
    id: 'port-3',
    barberId: 'barber-1',
    barberName: 'Hemerson',
    barberAvatar: '/barber-hemerson.jpg',
    title: 'Barba Esculpida & Alinhamento',
    styleTag: 'Barba de Respeito',
    category: 'barba',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    description: 'Contorno de bochechas com navalhete e toalha quente com essência de menta.',
    likesCount: 226,
    createdAt: '2026-08-30',
    suggestedServiceName: 'Barba simples',
  },
  {
    id: 'port-4',
    barberId: 'barber-2',
    barberName: 'Douglas',
    barberAvatar: '/barber-douglas.jpg',
    title: 'Mid Skin Fade com Texturização',
    styleTag: 'Mid Skin Fade',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1567894340315-735d7c361db0?w=800&auto=format&fit=crop&q=80',
    description: 'Degradê em 4 alturas partindo da pele com sombreamento uniforme.',
    likesCount: 310,
    createdAt: '2026-09-05',
    suggestedServiceName: 'Corte degradê',
  },
  {
    id: 'port-5',
    barberId: 'barber-2',
    barberName: 'Douglas',
    barberAvatar: '/barber-douglas.jpg',
    title: 'Low Taper Fade Urbano',
    styleTag: 'Taper Fade',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1517832606589-7629c339590a?w=800&auto=format&fit=crop&q=80',
    description: 'Desvanecimento apenas nas costeletas e na nuca, preservando o volume.',
    likesCount: 195,
    createdAt: '2026-09-01',
    suggestedServiceName: 'Corte degradê',
  },
  {
    id: 'port-6',
    barberId: 'barber-2',
    barberName: 'Douglas',
    barberAvatar: '/barber-douglas.jpg',
    title: 'High Fade com Topete Alto',
    styleTag: 'High Fade Navalhado',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&auto=format&fit=crop&q=80',
    description: 'Raspagem alta com transição limpa para clientes que buscam impacto.',
    likesCount: 168,
    createdAt: '2026-08-28',
    suggestedServiceName: 'Corte degradê',
  },
];
